# Generated by Django 4.1.2 on 2022-10-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0002_rename_ans_questions_answer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="answer",
            field=models.CharField(
                choices=[
                    ("options_1", "options_1"),
                    ("options_2", "options_2"),
                    ("options_3", "options_3"),
                    ("options_4", "options_4"),
                ],
                max_length=100,
            ),
        ),
    ]
