# Generated by Django 4.1.2 on 2022-10-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0003_alter_questions_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="answer",
            field=models.CharField(
                choices=[
                    ("option_1", "option_1"),
                    ("option_2", "option_2"),
                    ("option_3", "option_3"),
                    ("option_4", "option_4"),
                ],
                max_length=100,
            ),
        ),
    ]
